import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the Workflow SDK: the runtime entrypoints it writes into the
    // app router, and the bundle its Vitest plugin builds. Both already carry
    // their own `eslint-disable`, which then lints as an unused directive.
    "src/app/.well-known/workflow/**",
    ".workflow-vitest/**",
  ]),
]);

export default eslintConfig;
